- name: No Security Groups without ingress filtering being used
  ec2_group:
      name: "{{security_group_name}}"
      group_id: "{{security_group_id}}"
      description: "{{ security_group_description }}"
      vpc_id: "{{vpc_id}}"
      region: "{{aws_region}}"
      aws_secret_key: "{{aws_secret_key}}"
      aws_access_key: "{{aws_access_key}}"
      rules:
        - proto: tcp
          group_id: "{{security_group_id}}"
          from_port: "{{from_port}}"
          to_port: "{{to_port}}"
          cidr_ip: "{{cidr_range}}"
      rules_egress:
        - proto: tcp
          from_port: "{{from_port}}"
          to_port: "{{to_port}}"
          cidr_ip: "{{cidr_range}}"
          group_name: "{{security_group_name}}"
  register: sg_ingess_logfile_validation