---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  pre_tasks:
    - name: Validate Input
      assert:
        that:
        - aws_access_key is defined
        - aws_secret_key is defined
        - region is defined
        - vpc_id is defined
        - nacl_id is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: Restrict Network ACL Ingress from 0.0.0./0 to all ports
      ec2_vpc_nacl:
        nacl_id: " {{ nacl_id }}"
        vpc_id: "{ { vpc_id } }"
        state: present
        ingress:
          - [100, 'all', 'deny', '0.0.0.0/0', null, null,80,80]
   