- name: Enable Origin Access Identity
  community.aws.cloudfront_distribution:
    state: present
    distribution_id: "{{distribution_id}}"
    origins:
      - id: 'clopudfrontorigintestakshay.s3.us-east-1.amazonaws.com'
        domain_name: clopudfrontorigintestakshay.s3.us-east-1.amazonaws.com
#        s3_origin_access_identity_enabled : false
#        origin_path: /production
        s3_origin_config:
          origin_access_identity: origin-access-identity/cloudfront/12345