---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  vars:
    resources_file: "files/backup_resources.json"

  pre_tasks:
    - name: Validate Input
      assert:
        that:
          - aws_access_key is defined
          - aws_secret_key is defined
          - aws_region is defined
          - backup_plan_id is defined
          - iam_role_name is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: create backup plan json configuration
      template:
        src: ./backup_resources.j2
        dest: "{{resources_file}}"

    - name: enable table backup plan
      shell: >
        AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}"  aws backup create-backup-selection --cli-input-json file://files/backup_resources.json --region "{{aws_region}}"
      register: enable_backup_plan
      failed_when: enable_backup_plan.failed
    - debug: var=enable_backup_plan
   