---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  vars:
    queue_url: "https://sqs.{{aws_region}}.amazonaws.com/{{aws_account_id}}/{{queue_name}}"

  pre_tasks:
    - name: Validate Input
      assert:
        that:
          - aws_account_id is defined
          - aws_access_key is defined
          - aws_secret_key is defined
          - aws_region is defined
          - queue_name is defined
          - kms_key is defined
          - queue_url is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: Enable Server side encryption - SSE-KMS (Customer Managed Keys)
      shell: >
        AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws sqs set-queue-attributes --queue-url {{queue_url}} --attributes KmsMasterKeyId={{kms_key}} --region "{{aws_region}}"
      register: sqs_server_side_encryption
      failed_when: sqs_server_side_encryption.failed
    - debug: var=sqs_server_side_encryption