---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  vars:
    restapi_arn: arn:aws:apigateway:{{region}}::/restapis/{{api_id}}/stages/{{stage_name}}
    web_acl_arn: arn:aws:wafv2:{{region}}:{{aws_account_id}}:regional/webacl/{{web_acl_name}}/{{web_acl_id}}

  pre_tasks:
    - name: Validate Input
      assert:
        that:
        - aws_account_id is defined
        - aws_access_key is defined
        - aws_secret_key is defined
        - region is defined
        - api_id is defined
        - stage_name is defined
        - web_acl_name is defined
        - web_acl_id is defined
        - restapi_arn is defined
        - web_acl_arn is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: Associate WebAcl To Rest APIs
      shell: >
        AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws wafv2 associate-web-acl  --web-acl-arn "{{web_acl_arn}}" --resource-arn "{{restapi_arn}}" --region "{{region}}"
      register: web_acl_association
      failed_when: web_acl_association.stderr_lines
    - debug: var=web_acl_association
   