- name: Enable Cloudwatch Logging For REST APIs
  shell: >
    AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws apigateway update-stage --rest-api-id "{{api_id}}" --stage-name "{{stage_name}}" --patch-operations op=replace,path=/*/*/logging/dataTrace,value=true  --region "{{aws_region}}"
  register: enable_logging
  failed_when: enable_logging.stderr_lines
- debug: var=enable_logging


- name: Setting Log Level
  shell: >
    AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws apigateway update-stage --rest-api-id {{api_id}} --stage-name '{{stage_name}}' --patch-operations op=replace,path=/*/*/logging/loglevel,value=ERROR  --region "{{aws_region}}"
  register: log_level
  failed_when: log_level.stderr_lines
- debug: var=log_level

- name: Enable CloudWatch Metrics
  shell: >
    AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws apigateway update-stage --rest-api-id {{api_id}} --stage-name '{{stage_name}}' --patch-operations op=replace,path=/*/*/metrics/enabled,value=true  --region "{{aws_region}}"
  register: enable_cloudwatch_metrics
  failed_when: enable_cloudwatch_metrics.stderr_lines
- debug: var=enable_cloudwatch_metrics