---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  vars:
    log_group_name: "api_gateway_log_group_{{aws_account_id}}"
    policy_name: "api_gateway_lg_policy_{{aws_account_id}}"
    role_name: "api_gateway_lg_role_{{aws_account_id}}"
    policy_document_file: "./policy/policy_document.json"
    assume_policy_document_file: "./policy/assume_policy_document.json"

  pre_tasks:
    - name: Validate Input
      assert:
        that:
        - aws_account_id is defined
        - aws_access_key is defined
        - aws_secret_key is defined
        - aws_region is defined
        - api_id is defined
        - stage_name is defined
        - log_group_name is defined
        - policy_name is defined
        - role_name is defined
        - policy_document_file is defined
        - assume_policy_document_file is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: PCI -  Enable Logging For Rest API & WebSocket
      include_tasks: "{{ item }}"
      loop:
#          - ./tasks/configure_role_policy_group_and_logs.yaml
        - ./tasks/enable_api_logging.yaml
   