---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  pre_tasks:
    - name: Validate Input
      assert:
        that:
        - aws_access_key is defined
        - aws_secret_key is defined
        - region is defined
        - distribution_id is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: Enable S3 Origin Access Identity
      community.aws.cloudfront_distribution:
        state: present
        caller_reference: 1f62eb28-d419-4630-9bd3-531b2789f20b
        origins:
          - id: E299LBKFG9SX1H
            s3_origin_access_identity_enabled: yes
#            s3_origin_config:
#              origin_access_identity: origin-access-identity/cloudfront/E2C9XFNC92RLDS