- name: Create Security Configuration
  template:
    src: ./s3_encryption.j2
    dest: "{{s3_encryption_file}}"

- name: Enable S3 Encryption For Glue Development Endpoints & ETL Jobs
  shell: >
    AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws glue create-security-configuration --region us-east-1	--name cc-s3-encrypted-sec-config --encryption-configuration file://policy/s3_encryption.json --region {{ aws_region }}
  register: s3_encryption
  failed_when: s3_encryption.failed
- debug: var=s3_encryption.stdout
