---
- hosts: "localhost"
  connection: "local"
  gather_facts: false
  pre_tasks:
    - name: Validate Input
      assert:
        that:
          - aws_access_key is defined
          - aws_secret_key is defined
          - instance_id is defined
          - subnet_id is defined
  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer
    
    - name: Prowler - Check if any of the Elastic or Public IP are in Shodan (requires Shodan API KEY) -remediation
      include_tasks: "{{ item }}"
      loop:
        - ./tasks/create_pre_required_resources.yaml
        - ./tasks/change_ec2_public_ip_to_private_ip.yaml
        - ./tasks/destroy_resources_created_initially.yaml
   