- name: Ensure sns topic are publicly accessible
  community.aws.sns_topic:
      name: "{{sns_topic}}"
      state: present
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      region: "{{aws_region}}"
      display_name: "SNS Public Policy"
      policy: "{{ lookup('file', sns_document_file) }}"