---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  pre_tasks:
    - name: Validate Input
      assert:
        that:
          - aws_access_key is defined
          - aws_secret_key is defined
          - aws_region is defined
          - table_name is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: enable TTL on dynamodb table
      community.aws.dynamodb_ttl:
        state: enable
        table_name: "{{table_name}}"
        attribute_name: "{{table_name}}_ttl"
      register: enable_ttl
      failed_when: enable_ttl.failed
    - debug: var=enable_ttl
   