---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  pre_tasks:
    - name: Validate Input
      assert:
        that:
        - aws_access_key is defined
        - aws_secret_key is defined
        - aws_region is defined
        - api_id is defined
        - stage_name is defined
        - certificate_id is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer

    - name: API Gateway REST API stages configuration to use SSL certificates for backend authentication
      shell: >
        AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws apigateway update-stage --rest-api-id {{api_id}} --stage-name "{{stage_name}}" --patch-operations '[{"op":"replace","path":"/clientCertificateId","value":"{{certificate_id}}"}]'  --region "{{aws_region}}"
      register: assign_certificate
      failed_when: assign_certificate.stderr_lines
    - debug: var=assign_certificate
   