- name: Block EMR Public Access
  shell: >
    AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws ec2 describe-network-interfaces --query 'NetworkInterfaces[*].Association.PublicIp' --region {{ aws_region }}
  register: ec2_public_ips
  failed_when: ec2_public_ips.failed
- debug: var=ec2_public_ips.stdout

- block:
    - name: "Stop Execution"
      debug:
        msg: "No Need to execute further as No public ips Found"

    - meta: end_play
  when: ec2_public_ips.stdout == "[]"

- block:
    - name: "Get Ec2 Instance Ids"
      shell: >
        AWS_ACCESS_KEY_ID="{{aws_access_key}}" AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}" aws ec2 describe-instances --filter Name=ip-address,Values="{{ec2_public_ips.stdout}}" --query 'Reservations[].Instances[].InstanceId' --region {{ aws_region }}
      register: ec2_instances
    - debug: var=ec2_instances.stdout
