---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  vars:
    log_group_name: "management_event_log_group_{{aws_account_id}}"
    policy_name: "management_event_trail_lg_policy_{{aws_account_id}}"
    role_name: "management_event_trail_lg_role_{{aws_account_id}}"
    policy_document_file: "./policy/policy_document.json"
    assume_policy_document_file: "./policy/assume_policy_document.json"
    bucket_policy_file: "./policy/bucket_policy.json"
    s3_bucket_name: "management-event-trail-bucket-{{aws_account_id}}"
    trail_name: "management_event_trail_{{aws_account_id}}"
    aws_organization_changes_filter_exists: "True"

  pre_tasks:
    - name: Validate Input
      assert:
        that:
          - aws_access_key is defined
          - aws_secret_key is defined
          - aws_account_id is defined
          - aws_region is defined
          - aws_organization_changes_filter_exists is defined

  tasks:
    - name: Check ansible version
      when: (ansible_version.major == 2 and ansible_version.minor < 8 ) or (ansible_version.major < 2)
      run_once: yes
      fail:
        msg: Please use Ansible 2.8 or newer


    - name: .- Create Metric Filter & Alarms - CloudWatch
      include_tasks: "{{ item }}"
      loop:
        - ./tasks/create_prerequisite_configuration.yaml
        - ./tasks/aws_organization_change_alert.yaml
   